ДЗ 1
dtreskova/2020-1-Atom-QA-Python-D-Treskova pull request #1
Opened 2020-03-04 14:14 UTC by dtreskova

# Домашнее задание №1

Прошу @snicks92 или @z1ll1 проверить его.

Что было сделано:
* Написано по 5 автотестов с учетом техних тест-дизайна на каждую из структур данных 
    1. List
    1. Set
    1. Dictionary
    1. String
    1. Int
* Параметризовано по одному тесту на каждую структуру данных
* Проверен стиль кода линтером (pylint, flake8, pycodestyle)

2020-03-06 11:57 UTC, sniiick requested changes
Тесты на весь проект не запускаются из за неверного маски файлов (**tests_**)

2020-03-06 11:57 UTC, snicks92 commented on .gitignore
> +__pycache__
ПУстую строчку в конце

2020-03-06 20:42 UTC, dtreskova commented on .gitignore
> +__pycache__
Исправила название файлов и отредактировала некоторые тесты, добавила файл pytest.ini, где указала используемые маркеры
Добавила пустую строку в файл gitignore

2020-03-06 20:45 UTC, dtreskova commented
замечания исправлены, их можно проверять

2020-03-07 18:40 UTC, sniiick requested changes
Замечания ниже.

2020-03-07 18:40 UTC, sniiick commented on tests/test_check_dictionary.py
> +        assert not 'badly' in dictionary_fixture
`'badly' not in dictionary_fixture`

2020-03-07 18:40 UTC, sniiick commented on tests/test_check_dictionary.py
> +        assert dictionary_fixture[param] == 'poor' or 'good' or 'excellent'
Плохой ассерт из за приоритетов операторов сравнения, на лекции рассказывал. Тест будет всегда зеленым. И вот почему:
1. `dictionary_fixture[1] == 'poor' or 'good' or 'excellent'` -> True, потому что проверится только `dictionary_fixture[1] == 'poor'` и остальные условия не важны
2. `dictionary_fixture[2] == 'poor' or 'good' or 'excellent'` -> 'good', потому что первое условие не пройдет, а потом остальные условия не важны, а 'good' скастится в True
3. `dictionary_fixture[3] == 'poor' or 'good' or 'excellent'` -> то же 'good' и то же самое что в п2
4. `dictionary_fixture[1] == 'poor1' or 'good1' or 'excellent1'` -> 'good1' и снова зеленый тест
5. Более того, если на 1 ключ отдастся любое значение, то тест тоже будет зеленым по тем же причинам что и п2 п3 п4

2020-03-07 18:40 UTC, snicks92 commented on tests/test_check_int.py
> +    @pytest.mark.parametrize('param', [1, 100, 1000])
я бы еще добавил 0

2020-03-07 18:40 UTC, snicks92 commented on tests/test_check_set.py
> +        some_set = {}
Это не set

2020-03-12 19:27 UTC, dtreskova commented on tests/test_check_dictionary.py
> +        assert not 'badly' in dictionary_fixture
изменила проверку, проверяю, что 'good' есть в значениях словаря

2020-03-12 19:29 UTC, dtreskova commented on tests/test_check_dictionary.py
> +        assert dictionary_fixture[param] == 'poor' or 'good' or 'excellent'
изменила проверку, теперь проверяю в параметризации очистку словаря

2020-03-12 19:29 UTC, dtreskova commented on tests/test_check_int.py
> +    @pytest.mark.parametrize('param', [1, 100, 1000])
добавила

2020-03-12 19:30 UTC, dtreskova commented on tests/test_check_set.py
> +        some_set = {}
написала новый тест на проверку пересечения множеств, тип проверять не стала, поскольку этот проверка уже есть в параметризации

2020-03-12 19:34 UTC, dtreskova commented
замечания исправлены, можно проверять

2020-03-12 20:01 UTC, sniiick approved these changes
Ок

2020-03-12 20:01 UTC, merged